# -*- coding: utf-8 -*-
"""Копія записника "Код телеграм бота.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFW8PoFaIfFVIQiFRGENjht_UBvQIxfl

Інсталюємо необїідні бібліотеки.

Якщо будете запускати потім бота локально, то при встановлені бібліотек приберіть ! символ
"""


!pip install --upgrade google-generativeai
import telegram
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
import google.generativeai as genai
import os
import nest_asyncio
import re
import json
import requests # Import requests library for Notion API
import datetime # Import datetime for adding date to Notion

nest_asyncio.apply()

# Системні інструкції
SYSTEM_INSTRUCTIONS = """
Role: You are the "Nebula Mentor" an expert AI coach in Instructional Design and psychological counseling. Your mission is to train tarot readers to move from "Fatalistic Predictions" to "Empathetic Relationship Coaching" to increase user retention (Whale Business Model).
Core Objective:Evaluate expert responses based on three real-world cases. Identify Skill Gaps, provide immediate constructive feedback, and generate silent logs for Notion.
Formatting Rules (Strict):
NO Markdown symbols: Do NOT use **, ###, ---, or * for lists.
Plain Text only: Use only plain text for Telegram messages to ensure clean display, divide text into paragraphs for better reading. Do not introduse yourself, it was done automaticly after /start command.
Conciseness: Keep your feedback to 3-4 clear sentences.
Interaction & Feedback Logic:
Validation & Reinforcement: If the expert's response is good, start by naming exactly what they did well (e.g., "Excellent use of Empathic Needs Discovery!").
Constructive Correction: If there is a Skill Gap, do NOT say "Wrong." Instead, explain what is missing using the "Magic Window" concept—moving them from not knowing to being aware.
The Reframe: Suggest to try again giving some recomendations, but do not whrite "right" response, let user figure it out on their own.
Active Learning Flow: After a successful expert response, immediately present a new challenging query from Case 1, 2, or 3 to maintain momentum.
Evaluation Framework (7 Skill Gaps):
Empathetic Needs Discovery: Validating feelings/hidden needs.
Narrative Clarity: Simple and consistent card explanations.
Active Guidance (The Hook): Offering a plan to keep the user engaged.
Evidence-Based Practice: Explaining "why" based on cards, not guessing.
Emotional Regulation: Handling skepticism without escalating.
Avoidance of Fatalism: Avoiding "death sentences" like "You will break up".
Practicality (The Tool): Providing a concrete tool (e.g., communication script).
Here are 3 examples (you can use them or generate similar ones):
Scenario 1: Relationship Status
User Query: Is my ex coming back to me? We haven't spoken in three weeks.Incorrect: Let me check. The cards show a high probability he will return in nine weeks. But I also see another woman.Correct: I understand you need clarity during this silence. Let's use the cards to see what energy you can shift to attract the best outcome for yourself instead of just waiting .Key Gap: Fatalistic Prediction vs. Active Guidance.
Scenario 2: User Skepticism
User Query: Why did we fight? You're a psychic, you should already know! .Incorrect: I see you are angry. I am checking the cards now. I see a breakup next year.Correct: I feel your frustration after seven years of investment. Let's look at the internal conflicts affecting your communication to find a way to fix the situation .Key Gap: Emotional Escalation vs. Emotional Regulation .
Scenario 3: Decision Making
User Query: Things feel off lately. Should I stay or leave? .Incorrect: The cards suggest you need to find balance. Be patient and self-reflect before making a decision.Correct: Uncertainty is exhausting. Let's do a Needs Audit reading to see what you give, what you receive, and what is missing so you can make a firm choice.Key Gap: Vague Statements vs. Practical Tools .
Silent Notion Logging:
At the very end of EVERY response, you MUST include the following JSON block inside a hidden tag. This block will not be shown to the user if handled by the code.
[NOTION_DATA: {"Expert_ID": "user_id", "Detected_Gap": "Fatalistic Prediction/Empathetic Needs Discovery Failure/Lack of Narrative Clarity/Absence of Active Guidance/Poor Emotional Regulation/Lack of Evidence-Based Practicality/The "I Sort of Got It" Trap", "Mistake_Description": "Brief description", "Original_Response": "Expert text", "Suggested_Improvement": "NVC text", "Retention_Risk": "High/Medium/Low"}]
Tone: Professional, analytical, growth-oriented, and encouraging. Use English for all training content.
"""

# АПІ ключі - замініть на свої!
TELEGRAM_TOKEN = '8516575692:AAGOIVbGT5a4jkjIKI8zDAqySB8hcPPM6Io'  # Get from BotFather on Telegram
GEMINI_API_KEY = 'AIzaSyBWZk8JzW2Hm-aSPQ8i2deS6dwrdKwioDU'      # Get from Google AI Studio

# Notion API Keys - Replace with your own!
NOTION_TOKEN = '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' # Get from Notion Integrations
NOTION_DATABASE_ID = '30baf3d9b1248030a47ff4b579c6a9a3' # Get from your Notion database URL

# Конфігурація Геміні
genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel('gemini-2.5-flash') # ТУТ Задається ім'я моделі

# Функція для відправки даних до Notion
def send_to_notion(notion_data):
    headers = {
        "Authorization": f"Bearer {NOTION_TOKEN}",
        "Content-Type": "application/json",
        "Notion-Version": "2022-06-28",
    }

    current_time = datetime.datetime.now().isoformat() # Get current date and time

    new_page_data = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": {
            "Expert_ID": {"title": [{"text": {"content": str(notion_data.get('Expert_ID', 'N/A'))}}]}, # Using .get with default for safety
            "Detected_Gap": {"select": {"name": notion_data.get('Detected_Gap', 'N/A')}}, # Using .get with default for safety
            "Mistake_Description": {"rich_text": [{"text": {"content": notion_data.get('Mistake_Description', 'N/A')}}]}, # Using .get with default for safety
            "Original_Response": {"rich_text": [{"text": {"content": notion_data.get('Original_Response', 'N/A')}}]}, # Using .get with default for safety
            "Suggested_Improvement": {"rich_text": [{"text": {"content": notion_data.get('Suggested_Improvement', 'N/A')}}]}, # Using .get with default for safety
            "Retention_Risk": {"select": {"name": notion_data.get('Retention_Risk', 'N/A')}}},

    }

    try:
        response = requests.post("https://api.notion.com/v1/pages", headers=headers, json=new_page_data)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)
        print("Successfully sent data to Notion.")
    except requests.exceptions.RequestException as e:
        print(f"Error sending data to Notion: {e}")
        if e.response is not None:
            print(f"Notion API error response: {e.response.json()}") # Print Notion's detailed error

# Функція для обробки відповіді Геміні та вилучення даних для Notion
def process_gemini_response(full_response):
    # Шукаємо наш тег у відповіді
    pattern = r"\[NOTION_DATA: (\{.*?\})\]"
    match = re.search(pattern, full_response)

    if match:
        json_str = match.group(1)
        notion_data = json.loads(json_str)
        send_to_notion(notion_data) # Call the Notion sending function here

        # Видаляємо тех-дані з тексту для Telegram
        clean_text = re.sub(pattern, "", full_response).strip()
        return clean_text
    return full_response

# Відповідь на команду /start
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    welcome_message = "Welcome! 🔮 I’m your Nebula Mentor, here to help you turn every reading into a high-value connection. Together, we’ll master The Hook, refine your Narrative Clarity, and use Empathetic Discovery to skyrocket your retention and ratings. Ready for your first 5-minute challenge to boost your LTV?  Let’s dive in! 🚀"
    await update.message.reply_text(welcome_message)

# Додаємо інструкції як команду (оскільки вона згадана у вашому коді)
async def instructions(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(SYSTEM_INSTRUCTIONS)

# Обробляємо запити користувачів
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    user_message = update.message.text

    # Робимо запит до геміні
    try:
        chat = model.start_chat(history=[])
        response = chat.send_message(
            f"{SYSTEM_INSTRUCTIONS}\n\nUser query: {user_message}"
        )
        reply = process_gemini_response(response.text)
    except Exception as e:
        reply = f"Sorry, I encountered an error: {str(e)}"

    # Відповідаємо користувачу у боті
    await update.message.reply_text(reply)

# Обробляємо помилки
async def error(update: Update, context: ContextTypes.DEFAULT_TYPE):
    print(f"Update {update} caused error {context.error}")

# Create and configure the application
application = Application.builder().token(TELEGRAM_TOKEN).build()

# Додаємо модулі скрипта
application.add_handler(CommandHandler("start", start))
application.add_handler(CommandHandler("instructions", instructions))
application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
application.add_error_handler(error)

# Запускаємо бота
print("Bot is running...")
application.run_polling()

# Sample notion_data to test the JSON format
sample_notion_data = {
    "Expert_ID": "test_user_123",
    "Detected_Gap": "Fatalistic Prediction",
    "Mistake_Description": "The expert made a fatalistic prediction about a breakup.",
    "Original_Response": "You will break up next year.",
    "Suggested_Improvement": "Let's explore your current relationship dynamics to find areas for growth.",
    "Retention_Risk": "High"
}

print("Attempting to send sample data to Notion:")
send_to_notion(sample_notion_data)
print("Please check the output above for any Notion API error responses, if data didn't appear in Notion.")

